### ISSUE TITLE
Any updates in 2020?

### ISSUE THREAD

**Issue by zytakeshi** [wojons/cloudflare-lb#3]
Greetings from 2020.
I dug the whole internet and found this, but after days of research, I still couldn't get it running. 
First of all the API seems to be outdated as the Cloudflare API is now v4, I fixed the URL and got these error messages. 

`Getting data from CloudFlare
Traceback (most recent call last):
  File "cloudflare-lb.py", line 83, in <module>
    healthcheck(host)
  File "cloudflare-lb.py", line 59, in healthcheck
    if get_rec_id(RECORD, host[0]) == False: #needs to be added
  File "cloudflare-lb.py", line 72, in get_rec_id
    for y in RECS:
TypeError: 'bool' object is not iterable`

I am a newbie but I really need this, could you update it by any chance?

Thank you
Best regards
Takeshi.M

**Comment by HazeGaming** [comment]
> Greetings from 2020.
> I dug the whole internet and found this, but after days of research, I still couldn't get it running.
> First of all the API seems to be outdated as the Cloudflare API is now v4, I fixed the URL and got these error messages.
> 
> `Getting data from CloudFlare Traceback (most recent call last): File "cloudflare-lb.py", line 83, in <module> healthcheck(host) File "cloudflare-lb.py", line 59, in healthcheck if get_rec_id(RECORD, host[0]) == False: #needs to be added File "cloudflare-lb.py", line 72, in get_rec_id for y in RECS: TypeError: 'bool' object is not iterable`
> 
> I am a newbie but I really need this, could you update it by any chance?
> 
> Thank you
> Best regards
> Takeshi.M

Same for me! Really good script, but not working in 2020 ):
